server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/helloworldkim/spring-cloud-config.git
#          uri: file://C:\Users\USER\Desktop\study\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: busrefesh, health