server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/helloworldkim/spring-cloud-config.git
#          uri: file://C:\Users\USER\Desktop\study\git-local-repo